image: go1.2
script:
  - ulimit -n 2560
  - ./test_drone.sh
services:
  - redis:2.6
notify:
  email:
    recipients:
      - drone@clever.com
  hipchat:
    room: Clever-Dev-CI
    token: {{hipchatToken}}
    on_started: true
    on_success: true
    on_failure: true
